### ISSUE TITLE
Help with using this library

### ISSUE THREAD

**Issue by Ran-Mewo** [yuzawa-san/onnxruntime-java#176]
I can't figure out a way to do this easily using the library
```java
private Result encode(long[] tokens) throws OrtException {
    long[] attentionMasks = new long[tokens.length];
    for (int i = 0; i < tokens.length; i++) {
        attentionMasks[i] = 1L;
    }

    long[] tokenTypeIds = new long[tokens.length];
    for (int i = 0; i < tokens.length; i++) {
        tokenTypeIds[i] = 0L;
    }

    long[] shape = {1, tokens.length};

    try (
            OnnxTensor tokensTensor = OnnxTensor.createTensor(environment, LongBuffer.wrap(tokens), shape);
            OnnxTensor attentionMasksTensor = OnnxTensor.createTensor(environment, LongBuffer.wrap(attentionMasks), shape);
            OnnxTensor tokenTypeIdsTensor = OnnxTensor.createTensor(environment, LongBuffer.wrap(tokenTypeIds), shape)
    ) {
        Map<String, OnnxTensor> inputs = new HashMap<>();
        inputs.put("input_ids", tokensTensor);
        inputs.put("token_type_ids", tokenTypeIdsTensor);
        inputs.put("attention_mask", attentionMasksTensor);

        return session.run(inputs);
    }
}
```

I am trying to [use](https://huggingface.co/Xenova/e5-small-v2/resolve/main/onnx/model_quantized.onnx)
Also sorry I am sort of new to this entire space and I can't seem to get the official ONNX Java API working in my graal native enviroment

**Comment by yuzawa-san** [comment]
Based on that code snippet, it looks like you are using https://github.com/microsoft/onnxruntime/ (which does have its own separate java binding). Please open an issue there if that is the case. 

I have worked with that library in the past, but I do not know if it supports graalvm. I know it can be a bit finicky especially with JNI.

**Comment by Ran-Mewo** [comment]
Oh I meant like I am trying to replicate the code snippet I provided using this library
the code snippet uses https://github.com/microsoft/onnxruntime/ but I want to make it use this library

**Comment by yuzawa-san** [comment]
Please consult the example usages in this repo https://github.com/yuzawa-san/onnxruntime-java/blob/master/onnxruntime-sample-library/src/main/java/com/example/onnxruntime_sample_library/MyOracle.java and https://github.com/yuzawa-san/onnxruntime-java/blob/master/src/test/java/com/jyuzawa/onnxruntime/SessionTest.java

also there is some javadoc https://javadoc.io/doc/com.jyuzawa/onnxruntime

in general (with this library, or the other library, or even the tensorflow library) you will need to be careful to avoid accidental leaks or accessing the data after it is reclaimed/released. these libraries typically use native (off-heap) memory so they advise using try-with-resources. it would be unwise to pass a manually managed object (like a Result in your code, or a Transaction in my code) to the caller. i would advise doing something like:

```java
try (Transaction txn = session.newTransaction().build()) {
            double[] rawInput = new double[] {554354, 52345234, 143646};
            txn.addInput(0).asTensor().getDoubleBuffer().put(rawInput);
            txn.addOutput(0);
            NamedCollection<OnnxValue> output = txn.run();
            double[] rawOutput = new double[3];
            output.get(0).asTensor().getDoubleBuffer().get(rawOutput);
            return rawOutput;
// after we return and exit the try-with-resources, the output double buffer will be released when the Transaction is closed and the buffer not directly accessible to the caller.
        }
```
